name: AVR Monitor
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
permissions:
  contents: write
jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twilio pyyaml pytz
      - name: Run monitor
        env:
          AVR_USERNAME: ${{ secrets.AVR_USERNAME }}
          AVR_PASSWORD: ${{ secrets.AVR_PASSWORD }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
        run: |
          python monitor.py
      - name: Publish status.json to docs
        run: |
          mkdir -p docs
          cp status.json docs/status.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/status.json
          git commit -m "Update status.json [skip ci]" || true
          git push
