name: AVR Radiologist Alert

on:
  schedule:
    - cron: "0 * * * *"   # every hour, UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AVR_USERNAME: ${{ secrets.AVR_USERNAME }}
      AVR_PASSWORD: ${{ secrets.AVR_PASSWORD }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
      # Optional free fallback (email-to-SMS) if you want to enable it:
      # SMTP_HOST: ${{ secrets.SMTP_HOST }}
      # SMTP_PORT: ${{ secrets.SMTP_PORT }}
      # SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      # SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      # SMTP_FROM: ${{ secrets.SMTP_FROM }}
      HEADLESS: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run monitor
        run: |
          python monitor.py

      - name: Commit status artifacts (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/status.json docs/last_page.html docs/last_screenshot.png docs/color_samples.json || true
          git commit -m "Update status [skip ci]" || echo "No changes to commit"
          git push
