name: AVR Debug

on:
  workflow_dispatch:
    inputs:
      force_alert:
        type: boolean
        default: false
        description: "Force Telegram alert regardless of counts/window"
      timezone:
        type: string
        default: "America/New_York"
        description: "Optional TZ override for this run"

permissions:
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AVR_USERNAME: ${{ secrets.AVR_USERNAME }}
      AVR_PASSWORD: ${{ secrets.AVR_PASSWORD }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
      TIMEZONE: America/New_York

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz pyyaml

      - name: Apply workflow inputs to env
        shell: bash
        run: |
          if [ "${{ inputs.force_alert }}" = "true" ]; then
            echo "FORCE_ALERT=true" >> "$GITHUB_ENV"
          else
            echo "FORCE_ALERT=false" >> "$GITHUB_ENV"
          fi
          if [ -n "${{ inputs.timezone }}" ]; then
            echo "TIMEZONE=${{ inputs.timezone }}" >> "$GITHUB_ENV"
          fi
          echo "Using TIMEZONE=$TIMEZONE FORCE_ALERT=$FORCE_ALERT"

      - name: Telegram getMe (sanity)
        run: |
          if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
            curl -sS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" || true
          else
            echo "No TELEGRAM_BOT_TOKEN; skipping."
          fi

      - name: Telegram send debug ping (optional)
        run: |
          if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_IDS" ]; then
            TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            # Split on comma/semicolon/space
            for cid in $(echo "$TELEGRAM_CHAT_IDS" | tr ',;' ' '); do
              [ -z "$cid" ] && continue
              curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                -d "chat_id=$cid" -d "text=AVR Debug ping $TS" || true
              sleep 0.3
            done
          else
            echo "TELEGRAM_* not set; skipping debug ping."
          fi

      - name: Run monitor.py (creates/updates status.json)
        run: python monitor.py || true

      - name: Send Telegram alert via script
        run: python scripts/send_telegram.py || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            status.json
            docs/last_page.html
            docs/last_counts.csv
            docs/debug_*.html
            docs/debug_discover_*.html
            docs/*.json
          if-no-files-found: warn
          retention-days: 7
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Publish status.json to docs
        if: always()
        shell: bash
        run: |
          set -e
          mkdir -p docs
          if [ -f status.json ]; then
            cp status.json docs/status.json
          else
            echo '{}' > docs/status.json
          fi
          printf '{"time_utc":"%s","event":"%s","sha":"%s","ref":"%s","workflow":"%s"}\n' \
            "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            "${{ github.event_name }}" \
            "${{ github.sha }}" \
            "${{ github.ref }}" \
            "${{ github.workflow }}" > docs/last_monitor_run.json

          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add docs/status.json docs/last_monitor_run.json || true
          if ! git diff --cached --quiet; then
            git commit -m "AVR Debug: publish status.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
